Pop up
VuDej/Responsive-Web-Design pull request #11
Opened 2021-12-17 07:09 UTC by VuDej

fffff

2021-12-17 22:59 UTC, enaburekhan requested changes
Hi VuDej, 

Good job so far!

- [ ] Major highlights

- The codebase is clean, easy to read and understand.
- Passed linters checks

 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Code review by **Eric Enaburekhan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-12-17 22:59 UTC, enaburekhan commented on js/pop-up.js
> +                <img class="img-fluid pop-img" src="${project.img}" alt="">
- [ ] It will be nice to adjust the right margin so it can fit properly in mobile. see screen-shot:

![image](https://user-images.githubusercontent.com/51296741/146614771-91b87d73-c55c-41b5-be6a-adf775926b86.png)

2021-12-18 06:14 UTC, Cathella approved these changes
## 🟢 Status: Approved 🎉🎉

### Hi @VuDej ✋🏻, 

Great job working on the changes requested by the previous reviewer 💪🏻!
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## The Good Points 👍🏻

✔️ Linters are set correctly in the project repository. 
✔️ When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
✔️ When the user clicks (or taps) the close (X) button, the popup disappears.
✔️ The popup is responsive, it fits mobile and desktop sizes properly.
✔️ The popup follows the design for both desktop and mobile version from the chosen template in Figma.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-18 06:19 UTC, VuDej commented
merged pop-up branch

2021-12-18 06:19 UTC, merged